import { Passion } from "@/types";

// ~40 passions utilisees a l'onboarding (voir aussi PassionBubble)
export const PASSIONS: Passion[] = [
  { id: "football", label: "Football", icon: "⚽" },
  { id: "basketball", label: "Basketball", icon: "🏀" },
  { id: "tennis", label: "Tennis", icon: "🎾" },
  { id: "boxe", label: "Boxe", icon: "🥊" },
  { id: "musculation", label: "Musculation", icon: "🏋️" },
  { id: "running", label: "Running", icon: "🏃" },
  { id: "fitness", label: "Fitness", icon: "💪" },
  { id: "voyage", label: "Voyage", icon: "✈️" },
  { id: "cinema", label: "Cinema", icon: "🎬" },
  { id: "series", label: "Series", icon: "📺" },
  { id: "musique", label: "Musique", icon: "🎵" },
  { id: "dj", label: "DJ", icon: "🎧" },
  { id: "concerts", label: "Concerts", icon: "🎤" },
  { id: "mode", label: "Mode", icon: "👕" },
  { id: "luxe", label: "Luxe", icon: "💎" },
  { id: "gastronomie", label: "Gastronomie", icon: "🍽️" },
  { id: "cuisine", label: "Cuisine", icon: "👨‍🍳" },
  { id: "entrepreneuriat", label: "Entrepreneuriat", icon: "🚀" },
  { id: "startups", label: "Startups", icon: "🧪" },
  { id: "finance", label: "Finance", icon: "📈" },
  { id: "investissement", label: "Investissement", icon: "💰" },
  { id: "crypto", label: "Crypto", icon: "₿" },
  { id: "technologie", label: "Technologie", icon: "💻" },
  { id: "ia", label: "Intelligence artificielle", icon: "🤖" },
  { id: "gaming", label: "Gaming", icon: "🎮" },
  { id: "photographie", label: "Photographie", icon: "📷" },
  { id: "design", label: "Design", icon: "🎨" },
  { id: "lecture", label: "Lecture", icon: "📚" },
  { id: "art", label: "Art", icon: "🖼️" },
  { id: "automobile", label: "Automobile", icon: "🚗" },
  { id: "immobilier", label: "Immobilier", icon: "🏠" },
  { id: "ecologie", label: "Ecologie", icon: "🌱" },
  { id: "politique", label: "Politique internationale", icon: "🌍" },
  { id: "associations", label: "Associations", icon: "🤝" },
  { id: "humanitaire", label: "Humanitaire", icon: "❤️" },
  { id: "networking", label: "Networking", icon: "🔗" },
  { id: "nightlife", label: "Soirees / Nightlife", icon: "🎉" },
  { id: "culture", label: "Culture", icon: "🏛️" },
  { id: "developpement_perso", label: "Developpement personnel", icon: "🌟" },
  { id: "business", label: "Business", icon: "💼" },
];
